# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Shaowei
tagline:          'Code, Eat, Sleep'
description:      'I code for food'
url:              http://shaowei-su.github.io/
baseurl:          /

author:
  name:           'Shaowei Su'
  url:            https://twitter.com/ShaowSu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shaowei-su
