# Dependencies
markdown:         kramdown
highlighter:      rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# Permalinks
permalink:        pretty

# Setup
title:            Alibi
tagline:          'Code, Eat, Sleep'
description:      'My Life is Getting Better'
url:              http://shaowei-su.github.io/
baseurl:          /

author:
  name:           'Shaowei Su'
  url:            https://twitter.com/ShaowSu

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/shaowei-su

gems:		  [jekyll-paginate]
